name: Train model

on:
  push:
    paths:
      - "data/**"
      - "scripts/**"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.9.4

      - name: Install dependencies
        run: pixi install

      - name: Train model
        run: pixi run train

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v7
        with:
          name: trained-model
          path: model/model.joblib
